name: Continuos Integration

on: push

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.5.0
      - name: run install and test
        run: |
          npm install
          node --test api.test.js